<?php
/**
 * InstancesIdModifyPostRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurabx\OrthancPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Orthanc API
 *
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurabx\OrthancPHP\Model;

use \ArrayAccess;
use \Aurabx\OrthancPHP\ObjectSerializer;

/**
 * InstancesIdModifyPostRequest Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Aurabx\OrthancPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InstancesIdModifyPostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_instances__id__modify_post_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'force' => 'bool',
        'keep' => 'string[]',
        'keepSource' => 'bool',
        'privateCreator' => 'string',
        'remove' => 'string[]',
        'removePrivateTags' => 'bool',
        'replace' => 'object',
        'transcode' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'force' => null,
        'keep' => null,
        'keepSource' => null,
        'privateCreator' => null,
        'remove' => null,
        'removePrivateTags' => null,
        'replace' => null,
        'transcode' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'force' => false,
        'keep' => false,
        'keepSource' => false,
        'privateCreator' => false,
        'remove' => false,
        'removePrivateTags' => false,
        'replace' => false,
        'transcode' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'force' => 'Force',
        'keep' => 'Keep',
        'keepSource' => 'KeepSource',
        'privateCreator' => 'PrivateCreator',
        'remove' => 'Remove',
        'removePrivateTags' => 'RemovePrivateTags',
        'replace' => 'Replace',
        'transcode' => 'Transcode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'force' => 'setForce',
        'keep' => 'setKeep',
        'keepSource' => 'setKeepSource',
        'privateCreator' => 'setPrivateCreator',
        'remove' => 'setRemove',
        'removePrivateTags' => 'setRemovePrivateTags',
        'replace' => 'setReplace',
        'transcode' => 'setTranscode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'force' => 'getForce',
        'keep' => 'getKeep',
        'keepSource' => 'getKeepSource',
        'privateCreator' => 'getPrivateCreator',
        'remove' => 'getRemove',
        'removePrivateTags' => 'getRemovePrivateTags',
        'replace' => 'getReplace',
        'transcode' => 'getTranscode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('force', $data ?? [], null);
        $this->setIfExists('keep', $data ?? [], null);
        $this->setIfExists('keepSource', $data ?? [], null);
        $this->setIfExists('privateCreator', $data ?? [], null);
        $this->setIfExists('remove', $data ?? [], null);
        $this->setIfExists('removePrivateTags', $data ?? [], null);
        $this->setIfExists('replace', $data ?? [], null);
        $this->setIfExists('transcode', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets force
     *
     * @return bool|null
     */
    public function getForce()
    {
        return $this->container['force'];
    }

    /**
     * Sets force
     *
     * @param bool|null $force Allow the modification of tags related to DICOM identifiers, at the risk of breaking the DICOM model of the real world
     *
     * @return self
     */
    public function setForce($force)
    {
        if (is_null($force)) {
            throw new \InvalidArgumentException('non-nullable force cannot be null');
        }
        $this->container['force'] = $force;

        return $this;
    }

    /**
     * Gets keep
     *
     * @return string[]|null
     */
    public function getKeep()
    {
        return $this->container['keep'];
    }

    /**
     * Sets keep
     *
     * @param string[]|null $keep Keep the original value of the specified tags, to be chosen among the `StudyInstanceUID`, `SeriesInstanceUID` and `SOPInstanceUID` tags. Avoid this feature as much as possible, as this breaks the DICOM model of the real world.
     *
     * @return self
     */
    public function setKeep($keep)
    {
        if (is_null($keep)) {
            throw new \InvalidArgumentException('non-nullable keep cannot be null');
        }
        $this->container['keep'] = $keep;

        return $this;
    }

    /**
     * Gets keepSource
     *
     * @return bool|null
     */
    public function getKeepSource()
    {
        return $this->container['keepSource'];
    }

    /**
     * Sets keepSource
     *
     * @param bool|null $keepSource If set to `false`, instructs Orthanc to the remove original resources. By default, the original resources are kept in Orthanc.
     *
     * @return self
     */
    public function setKeepSource($keepSource)
    {
        if (is_null($keepSource)) {
            throw new \InvalidArgumentException('non-nullable keepSource cannot be null');
        }
        $this->container['keepSource'] = $keepSource;

        return $this;
    }

    /**
     * Gets privateCreator
     *
     * @return string|null
     */
    public function getPrivateCreator()
    {
        return $this->container['privateCreator'];
    }

    /**
     * Sets privateCreator
     *
     * @param string|null $privateCreator The private creator to be used for private tags in `Replace`
     *
     * @return self
     */
    public function setPrivateCreator($privateCreator)
    {
        if (is_null($privateCreator)) {
            throw new \InvalidArgumentException('non-nullable privateCreator cannot be null');
        }
        $this->container['privateCreator'] = $privateCreator;

        return $this;
    }

    /**
     * Gets remove
     *
     * @return string[]|null
     */
    public function getRemove()
    {
        return $this->container['remove'];
    }

    /**
     * Sets remove
     *
     * @param string[]|null $remove List of tags that must be removed from the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).
     *
     * @return self
     */
    public function setRemove($remove)
    {
        if (is_null($remove)) {
            throw new \InvalidArgumentException('non-nullable remove cannot be null');
        }
        $this->container['remove'] = $remove;

        return $this;
    }

    /**
     * Gets removePrivateTags
     *
     * @return bool|null
     */
    public function getRemovePrivateTags()
    {
        return $this->container['removePrivateTags'];
    }

    /**
     * Sets removePrivateTags
     *
     * @param bool|null $removePrivateTags Remove the private tags from the DICOM instances (defaults to `false`)
     *
     * @return self
     */
    public function setRemovePrivateTags($removePrivateTags)
    {
        if (is_null($removePrivateTags)) {
            throw new \InvalidArgumentException('non-nullable removePrivateTags cannot be null');
        }
        $this->container['removePrivateTags'] = $removePrivateTags;

        return $this;
    }

    /**
     * Gets replace
     *
     * @return object|null
     */
    public function getReplace()
    {
        return $this->container['replace'];
    }

    /**
     * Sets replace
     *
     * @param object|null $replace Associative array to change the value of some DICOM tags in the DICOM instances. Starting with Orthanc 1.9.4, paths to subsequences can be provided using the same syntax as the `dcmodify` command-line tool (wildcards are supported as well).
     *
     * @return self
     */
    public function setReplace($replace)
    {
        if (is_null($replace)) {
            throw new \InvalidArgumentException('non-nullable replace cannot be null');
        }
        $this->container['replace'] = $replace;

        return $this;
    }

    /**
     * Gets transcode
     *
     * @return string|null
     */
    public function getTranscode()
    {
        return $this->container['transcode'];
    }

    /**
     * Sets transcode
     *
     * @param string|null $transcode Transcode the DICOM instances to the provided DICOM transfer syntax: https://orthanc.uclouvain.be/book/faq/transcoding.html
     *
     * @return self
     */
    public function setTranscode($transcode)
    {
        if (is_null($transcode)) {
            throw new \InvalidArgumentException('non-nullable transcode cannot be null');
        }
        $this->container['transcode'] = $transcode;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


