<?php
/**
 * ModalitiesIdPutRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurabx\OrthancPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Orthanc API
 *
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurabx\OrthancPHP\Model;

use \ArrayAccess;
use \Aurabx\OrthancPHP\ObjectSerializer;

/**
 * ModalitiesIdPutRequest Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Aurabx\OrthancPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModalitiesIdPutRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_modalities__id__put_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'aET' => 'string',
        'allowEcho' => 'bool',
        'allowFind' => 'bool',
        'allowFindWorklist' => 'bool',
        'allowGet' => 'bool',
        'allowMove' => 'bool',
        'allowStorageCommitment' => 'bool',
        'allowStore' => 'bool',
        'allowTranscoding' => 'bool',
        'host' => 'string',
        'localAet' => 'string',
        'manufacturer' => 'string',
        'port' => 'float',
        'timeout' => 'float',
        'useDicomTls' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'aET' => null,
        'allowEcho' => null,
        'allowFind' => null,
        'allowFindWorklist' => null,
        'allowGet' => null,
        'allowMove' => null,
        'allowStorageCommitment' => null,
        'allowStore' => null,
        'allowTranscoding' => null,
        'host' => null,
        'localAet' => null,
        'manufacturer' => null,
        'port' => null,
        'timeout' => null,
        'useDicomTls' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'aET' => false,
        'allowEcho' => false,
        'allowFind' => false,
        'allowFindWorklist' => false,
        'allowGet' => false,
        'allowMove' => false,
        'allowStorageCommitment' => false,
        'allowStore' => false,
        'allowTranscoding' => false,
        'host' => false,
        'localAet' => false,
        'manufacturer' => false,
        'port' => false,
        'timeout' => false,
        'useDicomTls' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'aET' => 'AET',
        'allowEcho' => 'AllowEcho',
        'allowFind' => 'AllowFind',
        'allowFindWorklist' => 'AllowFindWorklist',
        'allowGet' => 'AllowGet',
        'allowMove' => 'AllowMove',
        'allowStorageCommitment' => 'AllowStorageCommitment',
        'allowStore' => 'AllowStore',
        'allowTranscoding' => 'AllowTranscoding',
        'host' => 'Host',
        'localAet' => 'LocalAet',
        'manufacturer' => 'Manufacturer',
        'port' => 'Port',
        'timeout' => 'Timeout',
        'useDicomTls' => 'UseDicomTls'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'aET' => 'setAET',
        'allowEcho' => 'setAllowEcho',
        'allowFind' => 'setAllowFind',
        'allowFindWorklist' => 'setAllowFindWorklist',
        'allowGet' => 'setAllowGet',
        'allowMove' => 'setAllowMove',
        'allowStorageCommitment' => 'setAllowStorageCommitment',
        'allowStore' => 'setAllowStore',
        'allowTranscoding' => 'setAllowTranscoding',
        'host' => 'setHost',
        'localAet' => 'setLocalAet',
        'manufacturer' => 'setManufacturer',
        'port' => 'setPort',
        'timeout' => 'setTimeout',
        'useDicomTls' => 'setUseDicomTls'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'aET' => 'getAET',
        'allowEcho' => 'getAllowEcho',
        'allowFind' => 'getAllowFind',
        'allowFindWorklist' => 'getAllowFindWorklist',
        'allowGet' => 'getAllowGet',
        'allowMove' => 'getAllowMove',
        'allowStorageCommitment' => 'getAllowStorageCommitment',
        'allowStore' => 'getAllowStore',
        'allowTranscoding' => 'getAllowTranscoding',
        'host' => 'getHost',
        'localAet' => 'getLocalAet',
        'manufacturer' => 'getManufacturer',
        'port' => 'getPort',
        'timeout' => 'getTimeout',
        'useDicomTls' => 'getUseDicomTls'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('aET', $data ?? [], null);
        $this->setIfExists('allowEcho', $data ?? [], null);
        $this->setIfExists('allowFind', $data ?? [], null);
        $this->setIfExists('allowFindWorklist', $data ?? [], null);
        $this->setIfExists('allowGet', $data ?? [], null);
        $this->setIfExists('allowMove', $data ?? [], null);
        $this->setIfExists('allowStorageCommitment', $data ?? [], null);
        $this->setIfExists('allowStore', $data ?? [], null);
        $this->setIfExists('allowTranscoding', $data ?? [], null);
        $this->setIfExists('host', $data ?? [], null);
        $this->setIfExists('localAet', $data ?? [], null);
        $this->setIfExists('manufacturer', $data ?? [], null);
        $this->setIfExists('port', $data ?? [], null);
        $this->setIfExists('timeout', $data ?? [], null);
        $this->setIfExists('useDicomTls', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets aET
     *
     * @return string|null
     */
    public function getAET()
    {
        return $this->container['aET'];
    }

    /**
     * Sets aET
     *
     * @param string|null $aET AET of the remote DICOM modality
     *
     * @return self
     */
    public function setAET($aET)
    {
        if (is_null($aET)) {
            throw new \InvalidArgumentException('non-nullable aET cannot be null');
        }
        $this->container['aET'] = $aET;

        return $this;
    }

    /**
     * Gets allowEcho
     *
     * @return bool|null
     */
    public function getAllowEcho()
    {
        return $this->container['allowEcho'];
    }

    /**
     * Sets allowEcho
     *
     * @param bool|null $allowEcho Whether to accept C-ECHO SCU commands issued by the remote modality
     *
     * @return self
     */
    public function setAllowEcho($allowEcho)
    {
        if (is_null($allowEcho)) {
            throw new \InvalidArgumentException('non-nullable allowEcho cannot be null');
        }
        $this->container['allowEcho'] = $allowEcho;

        return $this;
    }

    /**
     * Gets allowFind
     *
     * @return bool|null
     */
    public function getAllowFind()
    {
        return $this->container['allowFind'];
    }

    /**
     * Sets allowFind
     *
     * @param bool|null $allowFind Whether to accept C-FIND SCU commands issued by the remote modality
     *
     * @return self
     */
    public function setAllowFind($allowFind)
    {
        if (is_null($allowFind)) {
            throw new \InvalidArgumentException('non-nullable allowFind cannot be null');
        }
        $this->container['allowFind'] = $allowFind;

        return $this;
    }

    /**
     * Gets allowFindWorklist
     *
     * @return bool|null
     */
    public function getAllowFindWorklist()
    {
        return $this->container['allowFindWorklist'];
    }

    /**
     * Sets allowFindWorklist
     *
     * @param bool|null $allowFindWorklist Whether to accept C-FIND SCU commands for worklists issued by the remote modality
     *
     * @return self
     */
    public function setAllowFindWorklist($allowFindWorklist)
    {
        if (is_null($allowFindWorklist)) {
            throw new \InvalidArgumentException('non-nullable allowFindWorklist cannot be null');
        }
        $this->container['allowFindWorklist'] = $allowFindWorklist;

        return $this;
    }

    /**
     * Gets allowGet
     *
     * @return bool|null
     */
    public function getAllowGet()
    {
        return $this->container['allowGet'];
    }

    /**
     * Sets allowGet
     *
     * @param bool|null $allowGet Whether to accept C-GET SCU commands issued by the remote modality
     *
     * @return self
     */
    public function setAllowGet($allowGet)
    {
        if (is_null($allowGet)) {
            throw new \InvalidArgumentException('non-nullable allowGet cannot be null');
        }
        $this->container['allowGet'] = $allowGet;

        return $this;
    }

    /**
     * Gets allowMove
     *
     * @return bool|null
     */
    public function getAllowMove()
    {
        return $this->container['allowMove'];
    }

    /**
     * Sets allowMove
     *
     * @param bool|null $allowMove Whether to accept C-MOVE SCU commands issued by the remote modality
     *
     * @return self
     */
    public function setAllowMove($allowMove)
    {
        if (is_null($allowMove)) {
            throw new \InvalidArgumentException('non-nullable allowMove cannot be null');
        }
        $this->container['allowMove'] = $allowMove;

        return $this;
    }

    /**
     * Gets allowStorageCommitment
     *
     * @return bool|null
     */
    public function getAllowStorageCommitment()
    {
        return $this->container['allowStorageCommitment'];
    }

    /**
     * Sets allowStorageCommitment
     *
     * @param bool|null $allowStorageCommitment Whether to accept storage commitment requests issued by the remote modality
     *
     * @return self
     */
    public function setAllowStorageCommitment($allowStorageCommitment)
    {
        if (is_null($allowStorageCommitment)) {
            throw new \InvalidArgumentException('non-nullable allowStorageCommitment cannot be null');
        }
        $this->container['allowStorageCommitment'] = $allowStorageCommitment;

        return $this;
    }

    /**
     * Gets allowStore
     *
     * @return bool|null
     */
    public function getAllowStore()
    {
        return $this->container['allowStore'];
    }

    /**
     * Sets allowStore
     *
     * @param bool|null $allowStore Whether to accept C-STORE SCU commands issued by the remote modality
     *
     * @return self
     */
    public function setAllowStore($allowStore)
    {
        if (is_null($allowStore)) {
            throw new \InvalidArgumentException('non-nullable allowStore cannot be null');
        }
        $this->container['allowStore'] = $allowStore;

        return $this;
    }

    /**
     * Gets allowTranscoding
     *
     * @return bool|null
     */
    public function getAllowTranscoding()
    {
        return $this->container['allowTranscoding'];
    }

    /**
     * Sets allowTranscoding
     *
     * @param bool|null $allowTranscoding Whether to allow transcoding for operations initiated by this modality. This option applies to Orthanc C-GET SCP and to Orthanc C-STORE SCU. It only has an effect if the global option `EnableTranscoding` is set to `true`.
     *
     * @return self
     */
    public function setAllowTranscoding($allowTranscoding)
    {
        if (is_null($allowTranscoding)) {
            throw new \InvalidArgumentException('non-nullable allowTranscoding cannot be null');
        }
        $this->container['allowTranscoding'] = $allowTranscoding;

        return $this;
    }

    /**
     * Gets host
     *
     * @return string|null
     */
    public function getHost()
    {
        return $this->container['host'];
    }

    /**
     * Sets host
     *
     * @param string|null $host Host address of the remote DICOM modality (typically, an IP address)
     *
     * @return self
     */
    public function setHost($host)
    {
        if (is_null($host)) {
            throw new \InvalidArgumentException('non-nullable host cannot be null');
        }
        $this->container['host'] = $host;

        return $this;
    }

    /**
     * Gets localAet
     *
     * @return string|null
     */
    public function getLocalAet()
    {
        return $this->container['localAet'];
    }

    /**
     * Sets localAet
     *
     * @param string|null $localAet Whether to override the default DicomAet in the SCU connection initiated by Orthanc to this modality
     *
     * @return self
     */
    public function setLocalAet($localAet)
    {
        if (is_null($localAet)) {
            throw new \InvalidArgumentException('non-nullable localAet cannot be null');
        }
        $this->container['localAet'] = $localAet;

        return $this;
    }

    /**
     * Gets manufacturer
     *
     * @return string|null
     */
    public function getManufacturer()
    {
        return $this->container['manufacturer'];
    }

    /**
     * Sets manufacturer
     *
     * @param string|null $manufacturer Manufacturer of the remote DICOM modality (check configuration option `DicomModalities` for possible values
     *
     * @return self
     */
    public function setManufacturer($manufacturer)
    {
        if (is_null($manufacturer)) {
            throw new \InvalidArgumentException('non-nullable manufacturer cannot be null');
        }
        $this->container['manufacturer'] = $manufacturer;

        return $this;
    }

    /**
     * Gets port
     *
     * @return float|null
     */
    public function getPort()
    {
        return $this->container['port'];
    }

    /**
     * Sets port
     *
     * @param float|null $port TCP port of the remote DICOM modality
     *
     * @return self
     */
    public function setPort($port)
    {
        if (is_null($port)) {
            throw new \InvalidArgumentException('non-nullable port cannot be null');
        }
        $this->container['port'] = $port;

        return $this;
    }

    /**
     * Gets timeout
     *
     * @return float|null
     */
    public function getTimeout()
    {
        return $this->container['timeout'];
    }

    /**
     * Sets timeout
     *
     * @param float|null $timeout Whether to override the default DicomScuTimeout in the SCU connection initiated by Orthanc to this modality
     *
     * @return self
     */
    public function setTimeout($timeout)
    {
        if (is_null($timeout)) {
            throw new \InvalidArgumentException('non-nullable timeout cannot be null');
        }
        $this->container['timeout'] = $timeout;

        return $this;
    }

    /**
     * Gets useDicomTls
     *
     * @return bool|null
     */
    public function getUseDicomTls()
    {
        return $this->container['useDicomTls'];
    }

    /**
     * Sets useDicomTls
     *
     * @param bool|null $useDicomTls Whether to use DICOM TLS in the SCU connection initiated by Orthanc (new in Orthanc 1.9.0)
     *
     * @return self
     */
    public function setUseDicomTls($useDicomTls)
    {
        if (is_null($useDicomTls)) {
            throw new \InvalidArgumentException('non-nullable useDicomTls cannot be null');
        }
        $this->container['useDicomTls'] = $useDicomTls;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


