<?php
/**
 * ModalitiesIdStoreStraightPost200ResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  AurabxOrthancPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Orthanc API
 *
 * This is the full documentation of the [REST API](https://orthanc.uclouvain.be/book/users/rest.html) of Orthanc.<p>This reference is automatically generated from the source code of Orthanc. A [shorter cheat sheet](https://orthanc.uclouvain.be/book/users/rest-cheatsheet.html) is part of the Orthanc Book.<p>An earlier, manually crafted version from August 2019, is [still available](2019-08-orthanc-openapi.html), but is not up-to-date anymore ([source](https://groups.google.com/g/orthanc-users/c/NUiJTEICSl8/m/xKeqMrbqAAAJ)).
 *
 * The version of the OpenAPI document: 1.12.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace AurabxOrthancPHP\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ModalitiesIdStoreStraightPost200ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     AurabxOrthancPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ModalitiesIdStoreStraightPost200ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ModalitiesIdStoreStraightPost200Response"
     */
    public function testModalitiesIdStoreStraightPost200Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sOPClassUID"
     */
    public function testPropertySOPClassUID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sOPInstanceUID"
     */
    public function testPropertySOPInstanceUID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
